# Copyright (c) 2020 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

images:
  - name: docker.io/tpimenta/nginx-ldap-auth
    newName: reg.sighup.io/sighupio/fury/tpimenta/nginx-ldap-auth
    newTag: v1.0.6

commonLabels:
  app: nginx-ldap-auth

resources:
  - rbac.yaml
  - nginx-ldap-auth.yaml
