---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - cainjector
  - cert-manager-controller
  - webhook

commonLabels:
  app.kubernetes.io/version: 0.14.1
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/part-of: fury-kubernetes-ingress
  app.kubernetes.io/managed-by: kustomize
